disabled_rules: # 실행에서 제외할 룰 식별자들
  - identifier_name
  - force_try
  - force_cast
  - closure_parameter_position
opt_in_rules: # 일부 룰은 옵트 인 형태로 제공
included: # 린트 과정에 포함할 파일 경로. 이 항목이 존재하면 `--path`는 무시됨
excluded: # 린트 과정에서 무시할 파일 경로. `included`보다 우선순위 높음

line_length:
    warning: 130
    ignores_function_declarations: true
